### ISSUE TITLE
cherokee-postgis-install.sh has problems installing Postgres

### ISSUE THREAD

**Issue by charles-killian** [nursix/sahana-setup#2]
cherokee-postgis-install.sh will install postgresql-9.4 and then python-psycopg2.

When the script attempts to install postgresql-9.4-postgis it dies with

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgresql-9.4-postgis-2.3-scripts : Conflicts: postgresql-9.4-postgis-2.2-scripts but 2.2.2+dfsg-7~137.gite11228b.pgdg80+1 is to be installed
E: Unable to correct problems, you have held broken packages.

And it was going "SO" well.

I found this after running the configuration script and tried to open the eden URL. Did some looking around and found that postgres wasn't installed at all.

I ran the postgres installation code line by line and saw what I showed above.

Would appreciate some assistance with this.

Thanks!

Cheers!

Chuck...

**Comment by nursix** [comment]
A package postgresql-9.4-postgis-2.3-scripts doesn't exist in any stable Debian, so I guess you're using an unstable version (squeeze?).

You could either revert to a stable version (Jessie works best), or you can choose the postgis package version explicitly, like installing postgresql-9.4-postgis-2.2 instead of the default postgresql-9.4-postgis.

I would recommend the former, of course - stable distribution works best.

**Comment by nursix** [comment]
I found a fairly recent AWS image for Jessie that indeed tries to install postgresql-9.4-postgis-2.3 - but that dependency tree is broken. If you're working with AWS, this is what you may experience.

I'll try to hardcode the postgis-version, let's see how this works - will get back to you in a couple of minutes.

**Comment by nursix** [comment]
Yup, that does the trick. Will post an update of the script.

Don't wait for it - you can just edit the install-script an change postgresql-9.4-postgis into postgresql-9.4-postgis-2.2

**Comment by charles-killian** [comment]
Actually,

I am using Jessie. I always use a stable release.

Just to be sure I did a

cat /etc/*-release

It clearly shows that I have installed Jessie, darn it.

That’s the frustrating part.

I’ll modify the script and let you know how it goes.

Thanks for the quick reply.

Cheers!

Chuck…

**Comment by nursix** [comment]
Yeah, Chuck, see comments above - I guess you're using the AWS image I just found that has a broken dependency tree. Such things happen.

Hardcoding to postgis-2.2 works - update pushed. I just tested it again with that broken AWS image and it works fine. You should be able to go with that now.

**Comment by nursix** [comment]
Btw - thanks for posting the issue. Always welcome.

**Comment by charles-killian** [comment]
Dominic,

Works a treat!

Now I get to play with it.

I am an amateur radio operator (WB6YOK) that is involved with local emergency communications and other services for our local county government. I think this will meet more than just a few of our requirements.

Thanks again!

Cheers!

Chuck…
